name: Run Pytest (with uv)

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install uv
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
          echo "$HOME/.cargo/bin" >> $GITHUB_PATH

      - name: Create virtualenv with uv + install deps
        run: |
          uv venv
          source .venv/bin/activate
          uv pip install pytest pytest-mock
          uv sync

      - name: Run unit tests
        run: |
          source .venv/bin/activate
          uv run pytest
